version: '3'

services:

  mailserver:
    image: analogic/poste.io
    container_name: hosting-laplata.xyz
    restart: always
    network_mode: "host"
    expose:
      - "25"
      - "8181"
      - "4443"
      - "110"
      - "143"
      - "465"
      - "587"
      - "993"
      - "995"
    environment:
      - TZ=America/Managua
      - h=mail.hosting-laplata.xyz  # Direccion del servidor de mail hosting
      - HTTP_PORT=8181
      - HTTPS_PORT=4443
      - DISABLE_CLAMAV=TRUE
    volumes:
      - /mnt/mail:/data
